// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NotebookAI.Triples.TripleStore;

public partial class TripleDbContext : DbContext
{
    public TripleDbContext(DbContextOptions<TripleDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TripleEntity> TripleEntities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TripleEntity>(entity =>
        {
            entity.ToTable("TripleEntity");

            entity.HasIndex(e => e.Object, "IX_TripleEntity_Object");

            entity.HasIndex(e => new { e.Object, e.Predicate }, "IX_TripleEntity_Object_Predicate");

            entity.HasIndex(e => e.Predicate, "IX_TripleEntity_Predicate");

            entity.HasIndex(e => new { e.Predicate, e.Object }, "IX_TripleEntity_Predicate_Object");

            entity.HasIndex(e => e.Subject, "IX_TripleEntity_Subject");

            entity.HasIndex(e => new { e.Subject, e.Predicate, e.Object }, "IX_TripleEntity_Subject_Predicate_Object");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}