// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NotebookAI.Triples.TripleStore;

public partial class TripleEntity
{
    public string Id { get; set; }

    public string Subject { get; set; }

    public string Predicate { get; set; }

    public string Object { get; set; }

    public string GraphContext { get; set; }

    public string AnnotationMetadata { get; set; }

    public string UpdatedUtc { get; set; }

    public string CreatedUtc { get; set; }
}